export const bibleBooks = [
  // HEBREEUWS-ARAMESE GESCHRIFTEN / HEBREW-ARAMAIC SCRIPTURES (39 books)
  // Pentateuch (5) — dark shade
  { id: 1, nl: 'Genesis', en: 'Genesis', nlAbbr: 'Ge', enAbbr: 'Ge', testament: 'OT', group: 'law' },
  { id: 2, nl: 'Exodus', en: 'Exodus', nlAbbr: 'Ex', enAbbr: 'Ex', testament: 'OT', group: 'law' },
  { id: 3, nl: 'Leviticus', en: 'Leviticus', nlAbbr: 'Le', enAbbr: 'Le', testament: 'OT', group: 'law' },
  { id: 4, nl: 'Numeri', en: 'Numbers', nlAbbr: 'Nu', enAbbr: 'Nu', testament: 'OT', group: 'law' },
  { id: 5, nl: 'Deuteronomium', en: 'Deuteronomy', nlAbbr: 'De', enAbbr: 'De', testament: 'OT', group: 'law' },
  // Historical books (12) — light shade
  { id: 6, nl: 'Jozua', en: 'Joshua', nlAbbr: 'Joz', enAbbr: 'Jos', testament: 'OT', group: 'history' },
  { id: 7, nl: 'Rechters', en: 'Judges', nlAbbr: 'Re', enAbbr: 'Jg', testament: 'OT', group: 'history' },
  { id: 8, nl: 'Ruth', en: 'Ruth', nlAbbr: 'Ru', enAbbr: 'Ru', testament: 'OT', group: 'history' },
  { id: 9, nl: '1 Samuël', en: '1 Samuel', nlAbbr: '1Sa', enAbbr: '1Sa', testament: 'OT', group: 'history' },
  { id: 10, nl: '2 Samuël', en: '2 Samuel', nlAbbr: '2Sa', enAbbr: '2Sa', testament: 'OT', group: 'history' },
  { id: 11, nl: '1 Koningen', en: '1 Kings', nlAbbr: '1Kon', enAbbr: '1Ki', testament: 'OT', group: 'history' },
  { id: 12, nl: '2 Koningen', en: '2 Kings', nlAbbr: '2Kon', enAbbr: '2Ki', testament: 'OT', group: 'history' },
  { id: 13, nl: '1 Kronieken', en: '1 Chronicles', nlAbbr: '1Kr', enAbbr: '1Ch', testament: 'OT', group: 'history' },
  { id: 14, nl: '2 Kronieken', en: '2 Chronicles', nlAbbr: '2Kr', enAbbr: '2Ch', testament: 'OT', group: 'history' },
  { id: 15, nl: 'Ezra', en: 'Ezra', nlAbbr: 'Ezr', enAbbr: 'Ezr', testament: 'OT', group: 'history' },
  { id: 16, nl: 'Nehemia', en: 'Nehemiah', nlAbbr: 'Ne', enAbbr: 'Ne', testament: 'OT', group: 'history' },
  { id: 17, nl: 'Esther', en: 'Esther', nlAbbr: 'Es', enAbbr: 'Es', testament: 'OT', group: 'history' },
  // Poetic books (5) — medium shade
  { id: 18, nl: 'Job', en: 'Job', nlAbbr: 'Job', enAbbr: 'Job', testament: 'OT', group: 'poetry' },
  { id: 19, nl: 'Psalmen', en: 'Psalms', nlAbbr: 'Ps', enAbbr: 'Ps', testament: 'OT', group: 'poetry' },
  { id: 20, nl: 'Spreuken', en: 'Proverbs', nlAbbr: 'Sp', enAbbr: 'Pr', testament: 'OT', group: 'poetry' },
  { id: 21, nl: 'Prediker', en: 'Ecclesiastes', nlAbbr: 'Pr', enAbbr: 'Ec', testament: 'OT', group: 'poetry' },
  { id: 22, nl: 'Hooglied', en: 'Song of Solomon', nlAbbr: 'Hgl', enAbbr: 'Ca', testament: 'OT', group: 'poetry' },
  // Prophetic books (17) — darkest shade
  { id: 23, nl: 'Jesaja', en: 'Isaiah', nlAbbr: 'Jes', enAbbr: 'Isa', testament: 'OT', group: 'prophets' },
  { id: 24, nl: 'Jeremia', en: 'Jeremiah', nlAbbr: 'Jer', enAbbr: 'Jer', testament: 'OT', group: 'prophets' },
  { id: 25, nl: 'Klaagliederen', en: 'Lamentations', nlAbbr: 'Klg', enAbbr: 'La', testament: 'OT', group: 'prophets' },
  { id: 26, nl: 'Ezechiël', en: 'Ezekiel', nlAbbr: 'Ez', enAbbr: 'Eze', testament: 'OT', group: 'prophets' },
  { id: 27, nl: 'Daniël', en: 'Daniel', nlAbbr: 'Da', enAbbr: 'Da', testament: 'OT', group: 'prophets' },
  { id: 28, nl: 'Hosea', en: 'Hosea', nlAbbr: 'Ho', enAbbr: 'Ho', testament: 'OT', group: 'prophets' },
  { id: 29, nl: 'Joël', en: 'Joel', nlAbbr: 'Joë', enAbbr: 'Joe', testament: 'OT', group: 'prophets' },
  { id: 30, nl: 'Amos', en: 'Amos', nlAbbr: 'Am', enAbbr: 'Am', testament: 'OT', group: 'prophets' },
  { id: 31, nl: 'Obadja', en: 'Obadiah', nlAbbr: 'Ob', enAbbr: 'Ob', testament: 'OT', group: 'prophets' },
  { id: 32, nl: 'Jona', en: 'Jonah', nlAbbr: 'Jon', enAbbr: 'Jon', testament: 'OT', group: 'prophets' },
  { id: 33, nl: 'Micha', en: 'Micah', nlAbbr: 'Mi', enAbbr: 'Mic', testament: 'OT', group: 'prophets' },
  { id: 34, nl: 'Nahum', en: 'Nahum', nlAbbr: 'Na', enAbbr: 'Na', testament: 'OT', group: 'prophets' },
  { id: 35, nl: 'Habakuk', en: 'Habakkuk', nlAbbr: 'Hab', enAbbr: 'Hab', testament: 'OT', group: 'prophets' },
  { id: 36, nl: 'Zefanja', en: 'Zephaniah', nlAbbr: 'Ze', enAbbr: 'Zep', testament: 'OT', group: 'prophets' },
  { id: 37, nl: 'Haggaï', en: 'Haggai', nlAbbr: 'Hag', enAbbr: 'Hag', testament: 'OT', group: 'prophets' },
  { id: 38, nl: 'Zacharia', en: 'Zechariah', nlAbbr: 'Za', enAbbr: 'Zec', testament: 'OT', group: 'prophets' },
  { id: 39, nl: 'Maleachi', en: 'Malachi', nlAbbr: 'Mal', enAbbr: 'Mal', testament: 'OT', group: 'prophets' },
  // CHRISTELIJKE GRIEKSE GESCHRIFTEN / CHRISTIAN GREEK SCRIPTURES (27 books)
  // Gospels (4) — dark shade (same as law)
  { id: 40, nl: 'Mattheüs', en: 'Matthew', nlAbbr: 'Mt', enAbbr: 'Mt', testament: 'NT', group: 'gospels' },
  { id: 41, nl: 'Markus', en: 'Mark', nlAbbr: 'Mr', enAbbr: 'Mr', testament: 'NT', group: 'gospels' },
  { id: 42, nl: 'Lukas', en: 'Luke', nlAbbr: 'Lu', enAbbr: 'Lu', testament: 'NT', group: 'gospels' },
  { id: 43, nl: 'Johannes', en: 'John', nlAbbr: 'Jo', enAbbr: 'Joh', testament: 'NT', group: 'gospels' },
  // Acts (1) — light shade (same as history)
  { id: 44, nl: 'Handelingen', en: 'Acts', nlAbbr: 'Han', enAbbr: 'Ac', testament: 'NT', group: 'acts' },
  // Letters (21) — medium shade (same as poetry)
  { id: 45, nl: 'Romeinen', en: 'Romans', nlAbbr: 'Ro', enAbbr: 'Ro', testament: 'NT', group: 'epistles' },
  { id: 46, nl: '1 Korinthiërs', en: '1 Corinthians', nlAbbr: '1Kor', enAbbr: '1Co', testament: 'NT', group: 'epistles' },
  { id: 47, nl: '2 Korinthiërs', en: '2 Corinthians', nlAbbr: '2Kor', enAbbr: '2Co', testament: 'NT', group: 'epistles' },
  { id: 48, nl: 'Galaten', en: 'Galatians', nlAbbr: 'Ga', enAbbr: 'Ga', testament: 'NT', group: 'epistles' },
  { id: 49, nl: 'Efeziërs', en: 'Ephesians', nlAbbr: 'Ef', enAbbr: 'Eph', testament: 'NT', group: 'epistles' },
  { id: 50, nl: 'Filippenzen', en: 'Philippians', nlAbbr: 'Fil', enAbbr: 'Php', testament: 'NT', group: 'epistles' },
  { id: 51, nl: 'Kolossenzen', en: 'Colossians', nlAbbr: 'Kol', enAbbr: 'Col', testament: 'NT', group: 'epistles' },
  { id: 52, nl: '1 Thessalonicenzen', en: '1 Thessalonians', nlAbbr: '1Th', enAbbr: '1Th', testament: 'NT', group: 'epistles' },
  { id: 53, nl: '2 Thessalonicenzen', en: '2 Thessalonians', nlAbbr: '2Th', enAbbr: '2Th', testament: 'NT', group: 'epistles' },
  { id: 54, nl: '1 Timotheüs', en: '1 Timothy', nlAbbr: '1Ti', enAbbr: '1Ti', testament: 'NT', group: 'epistles' },
  { id: 55, nl: '2 Timotheüs', en: '2 Timothy', nlAbbr: '2Ti', enAbbr: '2Ti', testament: 'NT', group: 'epistles' },
  { id: 56, nl: 'Titus', en: 'Titus', nlAbbr: 'Tit', enAbbr: 'Tit', testament: 'NT', group: 'epistles' },
  { id: 57, nl: 'Filemon', en: 'Philemon', nlAbbr: 'Flm', enAbbr: 'Phm', testament: 'NT', group: 'epistles' },
  { id: 58, nl: 'Hebreeën', en: 'Hebrews', nlAbbr: 'Heb', enAbbr: 'Heb', testament: 'NT', group: 'epistles' },
  { id: 59, nl: 'Jakobus', en: 'James', nlAbbr: 'Jak', enAbbr: 'Jas', testament: 'NT', group: 'epistles' },
  { id: 60, nl: '1 Petrus', en: '1 Peter', nlAbbr: '1Pe', enAbbr: '1Pe', testament: 'NT', group: 'epistles' },
  { id: 61, nl: '2 Petrus', en: '2 Peter', nlAbbr: '2Pe', enAbbr: '2Pe', testament: 'NT', group: 'epistles' },
  { id: 62, nl: '1 Johannes', en: '1 John', nlAbbr: '1Jo', enAbbr: '1Jo', testament: 'NT', group: 'epistles' },
  { id: 63, nl: '2 Johannes', en: '2 John', nlAbbr: '2Jo', enAbbr: '2Jo', testament: 'NT', group: 'epistles' },
  { id: 64, nl: '3 Johannes', en: '3 John', nlAbbr: '3Jo', enAbbr: '3Jo', testament: 'NT', group: 'epistles' },
  { id: 65, nl: 'Judas', en: 'Jude', nlAbbr: 'Ju', enAbbr: 'Jude', testament: 'NT', group: 'epistles' },
  // Revelation (1) — darkest shade (same as prophets)
  { id: 66, nl: 'Openbaring', en: 'Revelation', nlAbbr: 'Opb', enAbbr: 'Re', testament: 'NT', group: 'revelation' },
];

// 4 color shades from JW Library Study Bible screenshots
// OT: law=dark, history=light, poetry=medium, prophets=darkest
// NT: gospels=dark, acts=light, epistles=medium, revelation=darkest
export const groupColors = {
  law:        { normal: '#3C384C', hover: '#2E2A3D', active: '#201C2E' },
  history:    { normal: '#847898', hover: '#6E6282', active: '#5A4E70' },
  poetry:     { normal: '#5E576E', hover: '#4A4358', active: '#3A3448' },
  prophets:   { normal: '#2E2840', hover: '#231D35', active: '#181228' },
  gospels:    { normal: '#3C384C', hover: '#2E2A3D', active: '#201C2E' },
  acts:       { normal: '#847898', hover: '#6E6282', active: '#5A4E70' },
  epistles:   { normal: '#5E576E', hover: '#4A4358', active: '#3A3448' },
  revelation: { normal: '#2E2840', hover: '#231D35', active: '#181228' },
};

// Descriptions sourced from NWT "The 66 Books of the Bible" (jw.org)
export const groupNames = {
  nl: {
    law: 'Pentateuch (5 boeken) — Van de schepping tot de vorming van de natie Israël',
    history: 'Historische boeken (12 boeken) — Israëls intocht in het beloofde land en de geschiedenis van de natie tot na de ballingschap',
    poetry: 'Poëtische boeken (5 boeken) — Wijze uitspraken en liederen',
    prophets: 'Profetische boeken (17 boeken) — Profetieën (voorspellingen) over Gods volk',
    gospels: 'De Evangeliën (4 boeken) — Jezus\' leven en dienst',
    acts: 'Handelingen van apostelen (1 boek) — De geschiedenis van het ontstaan van de christelijke gemeente en van het zendingswerk',
    epistles: 'Brieven (21 boeken) — Brieven aan christelijke gemeenten en aan afzonderlijke christenen',
    revelation: 'Openbaring (1 boek) — Profetische visioenen die aan de apostel Johannes werden gegeven',
  },
  en: {
    law: 'Pentateuch (5 books) — From creation to the founding of the ancient nation of Israel',
    history: 'Historical books (12 books) — Israel\'s entry into the Promised Land and the history of the nation through and after the exile',
    poetry: 'Poetic books (5 books) — Collections of wise sayings and songs',
    prophets: 'Prophetic books (17 books) — Prophecies, or predictions, concerning God\'s people',
    gospels: 'The four Gospels (4 books) — History of Jesus\' life and ministry',
    acts: 'Acts of Apostles (1 book) — History of the start of the Christian congregation and missionary activity',
    epistles: 'Letters (21 books) — Letters to Christian congregations and to individual Christians',
    revelation: 'Revelation (1 book) — Series of prophetic visions given to the apostle John',
  }
};

export const translations = {
  nl: {
    title: 'Bijbelboek Zoeker',
    subtitle: 'Leer waar de boeken zich bevinden',
    // UserSelect screen
    noUsers: 'Nog geen gebruikers. Voeg jezelf toe!',
    namePlaceholder: 'Je naam...',
    addBtn: 'Toevoegen',
    addUser: 'Gebruiker toevoegen',
    deleteTitle: 'Verwijderen',
    confirmDelete: 'Verwijder',
    confirmDeleteMsg: '{name} en alle voortgang verwijderen?',
    cancelDelete: 'Annuleer',
    confirmReset: 'Wissen',
    confirmResetMsg: 'Weet je zeker dat je je voortgang wilt wissen? Dit kan niet ongedaan worden gemaakt.',
    cancelReset: 'Annuleer',
    confirmImport: 'Herstel',
    cancelImport: 'Annuleer',
    confirmImportMsg: 'Dit overschrijft jouw huidige voortgang en instellingen.',
    confirmImportCrossMsg: '⚠️ Deze back-up is van "{backup}", je bent ingelogd als "{current}". Dit overschrijft {current}\'s voortgang en instellingen met die van {backup}.',
    errorMaxUsers: 'Maximum 10 gebruikers bereikt',
    errorDuplicate: 'Deze naam bestaat al',
    studyMode: 'Studie Modus',
    quizMode: 'Quiz Modus',
    score: 'Score',
    streak: 'Streak',
    of: 'van',
    tooSlow: 'Te traag',
    hebrewSection: 'HEBREEUWS-ARAMESE GESCHRIFTEN',
    greekSection: 'CHRISTELIJKE GRIEKSE GESCHRIFTEN',
    correct: 'Goed!',
    wrong: 'Verkeerd',
    share: 'Delen',
    resetProgress: 'Voortgang wissen',
    back: 'Terug',
    settingsTitle: 'Instellingen',
    gridTab: 'Raster',
    quizTab: 'Training',
    gridTitle: 'Raster',
    gridDesc: 'Kolommen en schermstand.',
    portrait: 'Portret',
    portraitDesc: '(rechtop)',
    landscape: 'Liggend',
    landscapeDesc: '(gedraaid)',
    orientation: 'Schermstand',
    orientationDesc: '(forceer of automatisch)',
    auto: 'Automatisch',
    portraitMode: 'Portret',
    landscapeMode: 'Liggend',
    masterySpeed: 'Meesterschapssnelheid',
    masterySpeedDesc: '(antwoord binnen deze tijd = beheerst)',
    fast: 'Snel',
    slow: 'Rustig',
    highlightFound: 'Beheerste boeken',
    highlightFoundDesc: '(markeer boeken die je beheerst)',
    autoScroll: 'Automatisch scrollen (Quiz & Studie)',
    autoScrollDesc: '(scroll naar het gevraagde boek bij elke vraag)',
    dataTab: 'Data',
    bookSelection: 'Boekselectie',
    bookSelectionDesc: '(in Studie Modus)',
    bookSelectionRandom: 'Willekeurig',
    bookSelectionFocused: 'Gefocust',
    dataTitle: 'Back-up',
    dataDesc: 'Maak of herstel een back-up van je voortgang en instellingen.',
    exportBtn: '📥 Maak back-up',
    importBtn: '📤 Herstel back-up',
    exportSuccess: 'Back-up gedownload!',
    importSuccess: 'Back-up hersteld!',
    importError: 'Ongeldig bestand.',
    importWarning: '⚠️ Herstellen overschrijft jouw huidige voortgang en instellingen.',
    hintReveal: 'Hint:',
    mastered: 'Beheerst',
    abbreviations: 'Afkortingen',
    abbreviationsDesc: '(portretmodus)',
    abbrAuto: 'Automatisch',
    abbrAlways: 'Altijd',
    abbrNever: 'Nooit',
    learningPace: 'Leertempo',
    learningPaceDesc: '',
    paceRelaxed: 'Ontspannen',
    paceBalanced: 'Gebalanceerd',
    paceIntensive: 'Intensief',
    paceRelaxedHint: 'Boeken komen minder vaak terug — ideaal als je af en toe oefent',
    paceBalancedHint: 'Aanbevolen — goede balans tussen inspanning en voortgang',
    paceIntensiveHint: 'Boeken komen vaak terug — ideaal als je regelmatig oefent',
    due: 'Te doen',
    readyToPractice: 'Klaar om te oefenen',
    practiced: 'Geoefend',
    allBooks: 'Alle boeken',
    books: 'boeken',
    studyChooseGroup: 'Kies groepen om te oefenen',
    startStudy: 'Start',
    wrongShowCorrect: 'Fout — kijk naar het blauwe vakje!',
    // Session summary
    sessionSummaryTitle: 'Sessie afgerond',
    sessionReviewed: 'boeken gereviewd',
    sessionMinutes: 'minuten',
    sessionCorrect: 'correct binnen de tijd',
    sessionNewBests: 'nieuw persoonlijk record',
    keepGoing: 'Verder oefenen',
    done: 'Klaar',
    // Personal best
    newBest: 'Nieuw record!',
    // Milestones
    milestone10: 'Goed zo! 10 boeken beheerst! 🎉',
    milestone20: 'Geweldig! 20 boeken beheerst! 🎉',
    milestone33: 'Halverwege! 33 van 66 boeken! 🎉',
    milestone39: 'Alle Hebreeuwse-Aramese Geschriften beheerst! 🎉',
    milestoneNT: 'Alle Christelijke Griekse Geschriften beheerst! 🎉',
    milestone50: 'Fantastisch! 50 boeken beheerst! 🎉',
    milestone66: 'Alle 66 boeken beheerst! 🏆',
    // Welcome back
    welcomeBack24h: 'Welkom terug! Laten we kijken wat je nog weet.',
    welcomeBack7d: 'Welkom terug! Ga verder waar je gebleven was — geen druk.',
  },
  en: {
    title: 'Bible Book Finder',
    subtitle: 'Learn where the books are located',
    // UserSelect screen
    noUsers: 'No users yet. Add yourself!',
    namePlaceholder: 'Your name...',
    addBtn: 'Add',
    addUser: 'Add user',
    deleteTitle: 'Delete',
    confirmDelete: 'Delete',
    confirmDeleteMsg: 'Delete {name} and all progress?',
    cancelDelete: 'Cancel',
    confirmReset: 'Reset',
    confirmResetMsg: 'Are you sure you want to reset your progress? This cannot be undone.',
    cancelReset: 'Cancel',
    confirmImport: 'Restore',
    cancelImport: 'Cancel',
    confirmImportMsg: 'This will overwrite your current progress and settings.',
    confirmImportCrossMsg: '⚠️ This backup is from "{backup}", you are logged in as "{current}". This will overwrite {current}\'s progress and settings with {backup}\'s.',
    errorMaxUsers: 'Maximum 10 users reached',
    errorDuplicate: 'This name already exists',
    studyMode: 'Study Mode',
    quizMode: 'Quiz Mode',
    score: 'Score',
    streak: 'Streak',
    of: 'of',
    tooSlow: 'Too slow',
    hebrewSection: 'HEBREW-ARAMAIC SCRIPTURES',
    greekSection: 'CHRISTIAN GREEK SCRIPTURES',
    correct: 'Correct!',
    wrong: 'Wrong',
    share: 'Share',
    resetProgress: 'Reset Progress',
    back: 'Back',
    settingsTitle: 'Settings',
    gridTab: 'Grid',
    quizTab: 'Training',
    gridTitle: 'Grid',
    gridDesc: 'Columns and orientation.',
    portrait: 'Portrait',
    portraitDesc: '(upright)',
    landscape: 'Landscape',
    landscapeDesc: '(rotated)',
    orientation: 'Orientation',
    orientationDesc: '(force or auto)',
    auto: 'Auto',
    portraitMode: 'Portrait',
    landscapeMode: 'Landscape',
    masterySpeed: 'Mastery Speed',
    masterySpeedDesc: '(answer within this time = mastered)',
    fast: 'Fast',
    slow: 'Relaxed',
    highlightFound: 'Mastered books',
    highlightFoundDesc: '(highlight mastered books)',
    autoScroll: 'Auto-scroll (Quiz & Study)',
    autoScrollDesc: '(scroll to the asked book on each question)',
    dataTab: 'Data',
    bookSelection: 'Book selection',
    bookSelectionDesc: '(in Study Mode)',
    bookSelectionRandom: 'Random',
    bookSelectionFocused: 'Focused',
    dataTitle: 'Backup',
    dataDesc: 'Create or restore a backup of your progress and settings.',
    exportBtn: '📥 Create Backup',
    importBtn: '📤 Restore Backup',
    exportSuccess: 'Backup downloaded!',
    importSuccess: 'Backup restored!',
    importError: 'Invalid file.',
    importWarning: '⚠️ Restoring will overwrite your current progress and settings.',
    hintReveal: 'Hint:',
    mastered: 'Mastered',
    abbreviations: 'Abbreviations',
    abbreviationsDesc: '(portrait mode)',
    abbrAuto: 'Auto',
    abbrAlways: 'Always',
    abbrNever: 'Never',
    learningPace: 'Learning pace',
    learningPaceDesc: '',
    paceRelaxed: 'Relaxed',
    paceBalanced: 'Balanced',
    paceIntensive: 'Intensive',
    paceRelaxedHint: 'Books come back less often — best if you practice occasionally',
    paceBalancedHint: 'Recommended — good balance between effort and progress',
    paceIntensiveHint: 'Books come back frequently — best if you practice often',
    due: 'Due',
    readyToPractice: 'Ready to practice',
    practiced: 'Practiced',
    allBooks: 'All Books',
    books: 'books',
    studyChooseGroup: 'Choose groups to study',
    startStudy: 'Start',
    wrongShowCorrect: 'Wrong — look for the blue cell!',
    // Session summary
    sessionSummaryTitle: 'Session complete',
    sessionReviewed: 'books reviewed',
    sessionMinutes: 'minutes',
    sessionCorrect: 'correct within time',
    sessionNewBests: 'new personal record',
    keepGoing: 'Keep going',
    done: 'Done',
    // Personal best
    newBest: 'New record!',
    // Milestones
    milestone10: 'Nice! 10 books mastered! 🎉',
    milestone20: 'Great! 20 books mastered! 🎉',
    milestone33: 'Halfway! 33 of 66 books! 🎉',
    milestone39: 'All Hebrew-Aramaic Scriptures mastered! 🎉',
    milestoneNT: 'All Christian Greek Scriptures mastered! 🎉',
    milestone50: 'Fantastic! 50 books mastered! 🎉',
    milestone66: 'All 66 books mastered! 🏆',
    // Welcome back
    welcomeBack24h: 'Welcome back! Let\'s see what you remember.',
    welcomeBack7d: 'Welcome back! Pick up where you left off — no pressure.',
  }
};
