export const bibleBooks = [
  // HEBREEUWS-ARAMESE GESCHRIFTEN / HEBREW-ARAMAIC SCRIPTURES (39 books)
  { id: 1, nl: 'Genesis', en: 'Genesis', nlAbbr: 'Ge', enAbbr: 'Ge', testament: 'OT', group: 'law' },
  { id: 2, nl: 'Exodus', en: 'Exodus', nlAbbr: 'Ex', enAbbr: 'Ex', testament: 'OT', group: 'law' },
  { id: 3, nl: 'Leviticus', en: 'Leviticus', nlAbbr: 'Le', enAbbr: 'Le', testament: 'OT', group: 'law' },
  { id: 4, nl: 'Numeri', en: 'Numbers', nlAbbr: 'Nu', enAbbr: 'Nu', testament: 'OT', group: 'law' },
  { id: 5, nl: 'Deuteronomium', en: 'Deuteronomy', nlAbbr: 'De', enAbbr: 'De', testament: 'OT', group: 'law' },
  { id: 6, nl: 'Jozua', en: 'Joshua', nlAbbr: 'Joz', enAbbr: 'Jos', testament: 'OT', group: 'history' },
  { id: 7, nl: 'Rechters', en: 'Judges', nlAbbr: 'Re', enAbbr: 'Jdg', testament: 'OT', group: 'history' },
  { id: 8, nl: 'Ruth', en: 'Ruth', nlAbbr: 'Ru', enAbbr: 'Ru', testament: 'OT', group: 'history' },
  { id: 9, nl: '1 Samuël', en: '1 Samuel', nlAbbr: '1Sa', enAbbr: '1Sa', testament: 'OT', group: 'history' },
  { id: 10, nl: '2 Samuël', en: '2 Samuel', nlAbbr: '2Sa', enAbbr: '2Sa', testament: 'OT', group: 'history' },
  { id: 11, nl: '1 Koningen', en: '1 Kings', nlAbbr: '1Kon', enAbbr: '1Kgs', testament: 'OT', group: 'history' },
  { id: 12, nl: '2 Koningen', en: '2 Kings', nlAbbr: '2Kon', enAbbr: '2Kgs', testament: 'OT', group: 'history' },
  { id: 13, nl: '1 Kronieken', en: '1 Chronicles', nlAbbr: '1Kr', enAbbr: '1Ch', testament: 'OT', group: 'history' },
  { id: 14, nl: '2 Kronieken', en: '2 Chronicles', nlAbbr: '2Kr', enAbbr: '2Ch', testament: 'OT', group: 'history' },
  { id: 15, nl: 'Ezra', en: 'Ezra', nlAbbr: 'Ezr', enAbbr: 'Ezr', testament: 'OT', group: 'history' },
  { id: 16, nl: 'Nehemia', en: 'Nehemiah', nlAbbr: 'Ne', enAbbr: 'Ne', testament: 'OT', group: 'history' },
  { id: 17, nl: 'Esther', en: 'Esther', nlAbbr: 'Es', enAbbr: 'Es', testament: 'OT', group: 'history' },
  { id: 18, nl: 'Job', en: 'Job', nlAbbr: 'Job', enAbbr: 'Job', testament: 'OT', group: 'poetry' },
  { id: 19, nl: 'Psalmen', en: 'Psalms', nlAbbr: 'Ps', enAbbr: 'Ps', testament: 'OT', group: 'poetry' },
  { id: 20, nl: 'Spreuken', en: 'Proverbs', nlAbbr: 'Sp', enAbbr: 'Pr', testament: 'OT', group: 'poetry' },
  { id: 21, nl: 'Prediker', en: 'Ecclesiastes', nlAbbr: 'Pr', enAbbr: 'Ec', testament: 'OT', group: 'poetry' },
  { id: 22, nl: 'Hooglied', en: 'Song of Solomon', nlAbbr: 'Hgl', enAbbr: 'Ca', testament: 'OT', group: 'poetry' },
  { id: 23, nl: 'Jesaja', en: 'Isaiah', nlAbbr: 'Jes', enAbbr: 'Isa', testament: 'OT', group: 'prophets' },
  { id: 24, nl: 'Jeremia', en: 'Jeremiah', nlAbbr: 'Jer', enAbbr: 'Jer', testament: 'OT', group: 'prophets' },
  { id: 25, nl: 'Klaagliederen', en: 'Lamentations', nlAbbr: 'Klg', enAbbr: 'La', testament: 'OT', group: 'prophets' },
  { id: 26, nl: 'Ezechiël', en: 'Ezekiel', nlAbbr: 'Ez', enAbbr: 'Eze', testament: 'OT', group: 'prophets' },
  { id: 27, nl: 'Daniël', en: 'Daniel', nlAbbr: 'Da', enAbbr: 'Da', testament: 'OT', group: 'prophets' },
  { id: 28, nl: 'Hosea', en: 'Hosea', nlAbbr: 'Ho', enAbbr: 'Ho', testament: 'OT', group: 'prophets' },
  { id: 29, nl: 'Joël', en: 'Joel', nlAbbr: 'Joë', enAbbr: 'Joe', testament: 'OT', group: 'prophets' },
  { id: 30, nl: 'Amos', en: 'Amos', nlAbbr: 'Am', enAbbr: 'Am', testament: 'OT', group: 'prophets' },
  { id: 31, nl: 'Obadja', en: 'Obadiah', nlAbbr: 'Ob', enAbbr: 'Ob', testament: 'OT', group: 'prophets' },
  { id: 32, nl: 'Jona', en: 'Jonah', nlAbbr: 'Jon', enAbbr: 'Jon', testament: 'OT', group: 'prophets' },
  { id: 33, nl: 'Micha', en: 'Micah', nlAbbr: 'Mi', enAbbr: 'Mic', testament: 'OT', group: 'prophets' },
  { id: 34, nl: 'Nahum', en: 'Nahum', nlAbbr: 'Na', enAbbr: 'Na', testament: 'OT', group: 'prophets' },
  { id: 35, nl: 'Habakuk', en: 'Habakkuk', nlAbbr: 'Hab', enAbbr: 'Hab', testament: 'OT', group: 'prophets' },
  { id: 36, nl: 'Zefanja', en: 'Zephaniah', nlAbbr: 'Ze', enAbbr: 'Zep', testament: 'OT', group: 'prophets' },
  { id: 37, nl: 'Haggaï', en: 'Haggai', nlAbbr: 'Hag', enAbbr: 'Hag', testament: 'OT', group: 'prophets' },
  { id: 38, nl: 'Zacharia', en: 'Zechariah', nlAbbr: 'Za', enAbbr: 'Zec', testament: 'OT', group: 'prophets' },
  { id: 39, nl: 'Maleachi', en: 'Malachi', nlAbbr: 'Mal', enAbbr: 'Mal', testament: 'OT', group: 'prophets' },
  // CHRISTELIJKE GRIEKSE GESCHRIFTEN / CHRISTIAN GREEK SCRIPTURES (27 books)
  { id: 40, nl: 'Mattheüs', en: 'Matthew', nlAbbr: 'Mt', enAbbr: 'Mt', testament: 'NT', group: 'gospels' },
  { id: 41, nl: 'Markus', en: 'Mark', nlAbbr: 'Mr', enAbbr: 'Mr', testament: 'NT', group: 'gospels' },
  { id: 42, nl: 'Lukas', en: 'Luke', nlAbbr: 'Lu', enAbbr: 'Lu', testament: 'NT', group: 'gospels' },
  { id: 43, nl: 'Johannes', en: 'John', nlAbbr: 'Jo', enAbbr: 'Joh', testament: 'NT', group: 'gospels' },
  { id: 44, nl: 'Handelingen', en: 'Acts', nlAbbr: 'Han', enAbbr: 'Ac', testament: 'NT', group: 'history' },
  { id: 45, nl: 'Romeinen', en: 'Romans', nlAbbr: 'Ro', enAbbr: 'Ro', testament: 'NT', group: 'epistles' },
  { id: 46, nl: '1 Korinthiërs', en: '1 Corinthians', nlAbbr: '1Kor', enAbbr: '1Co', testament: 'NT', group: 'epistles' },
  { id: 47, nl: '2 Korinthiërs', en: '2 Corinthians', nlAbbr: '2Kor', enAbbr: '2Co', testament: 'NT', group: 'epistles' },
  { id: 48, nl: 'Galaten', en: 'Galatians', nlAbbr: 'Ga', enAbbr: 'Ga', testament: 'NT', group: 'epistles' },
  { id: 49, nl: 'Efeziërs', en: 'Ephesians', nlAbbr: 'Ef', enAbbr: 'Eph', testament: 'NT', group: 'epistles' },
  { id: 50, nl: 'Filippenzen', en: 'Philippians', nlAbbr: 'Fil', enAbbr: 'Php', testament: 'NT', group: 'epistles' },
  { id: 51, nl: 'Kolossenzen', en: 'Colossians', nlAbbr: 'Kol', enAbbr: 'Col', testament: 'NT', group: 'epistles' },
  { id: 52, nl: '1 Thessalonicenzen', en: '1 Thessalonians', nlAbbr: '1Th', enAbbr: '1Th', testament: 'NT', group: 'epistles' },
  { id: 53, nl: '2 Thessalonicenzen', en: '2 Thessalonians', nlAbbr: '2Th', enAbbr: '2Th', testament: 'NT', group: 'epistles' },
  { id: 54, nl: '1 Timotheüs', en: '1 Timothy', nlAbbr: '1Ti', enAbbr: '1Ti', testament: 'NT', group: 'epistles' },
  { id: 55, nl: '2 Timotheüs', en: '2 Timothy', nlAbbr: '2Ti', enAbbr: '2Ti', testament: 'NT', group: 'epistles' },
  { id: 56, nl: 'Titus', en: 'Titus', nlAbbr: 'Tit', enAbbr: 'Tit', testament: 'NT', group: 'epistles' },
  { id: 57, nl: 'Filemon', en: 'Philemon', nlAbbr: 'Flm', enAbbr: 'Phm', testament: 'NT', group: 'epistles' },
  { id: 58, nl: 'Hebreeën', en: 'Hebrews', nlAbbr: 'Heb', enAbbr: 'Heb', testament: 'NT', group: 'epistles' },
  { id: 59, nl: 'Jakobus', en: 'James', nlAbbr: 'Jak', enAbbr: 'Jas', testament: 'NT', group: 'epistles' },
  { id: 60, nl: '1 Petrus', en: '1 Peter', nlAbbr: '1Pe', enAbbr: '1Pe', testament: 'NT', group: 'epistles' },
  { id: 61, nl: '2 Petrus', en: '2 Peter', nlAbbr: '2Pe', enAbbr: '2Pe', testament: 'NT', group: 'epistles' },
  { id: 62, nl: '1 Johannes', en: '1 John', nlAbbr: '1Jo', enAbbr: '1Jo', testament: 'NT', group: 'epistles' },
  { id: 63, nl: '2 Johannes', en: '2 John', nlAbbr: '2Jo', enAbbr: '2Jo', testament: 'NT', group: 'epistles' },
  { id: 64, nl: '3 Johannes', en: '3 John', nlAbbr: '3Jo', enAbbr: '3Jo', testament: 'NT', group: 'epistles' },
  { id: 65, nl: 'Judas', en: 'Jude', nlAbbr: 'Ju', enAbbr: 'Jude', testament: 'NT', group: 'epistles' },
  { id: 66, nl: 'Openbaring', en: 'Revelation', nlAbbr: 'Opb', enAbbr: 'Re', testament: 'NT', group: 'revelation' },
];

// Color groups matching screenshots exactly
export const groupColors = {
  law:       { normal: '#3b3549', hover: '#2d2840', active: '#1e1a30' },
  history:   { normal: '#746d85', hover: '#5e5770', active: '#4a4458' },
  poetry:    { normal: '#5d556e', hover: '#4a4358', active: '#3a3448' },
  prophets:  { normal: '#2e2840', hover: '#231d35', active: '#181228' },
  gospels:   { normal: '#3b3549', hover: '#2d2840', active: '#1e1a30' },
  epistles:  { normal: '#5d556e', hover: '#4a4358', active: '#3a3448' },
  revelation:{ normal: '#2e2840', hover: '#231d35', active: '#181228' },
};

export const translations = {
  nl: {
    title: 'Bijbelboek Zoeker',
    subtitle: 'Leer waar de boeken zich bevinden',
    studyMode: 'Studie Modus',
    quizMode: 'Quiz Modus',
    score: 'Score',
    streak: 'Rij',
    best: 'Beste',
    found: 'Gevonden',
    of: 'van',
    time: 'Tijd',
    beat: 'Versla',
    tooSlow: 'Te traag',
    hebrewSection: 'HEBREEUWS-ARAMESE GESCHRIFTEN',
    greekSection: 'CHRISTELIJKE GRIEKSE GESCHRIFTEN',
    correct: 'Goed!',
    wrong: 'Verkeerd',
    share: 'Delen',
    shareText: 'Ik heb {found} van 66 bijbelboeken gevonden!',
    resetProgress: 'Voortgang wissen',
    back: 'Terug',
    settingsTitle: 'Instellingen',
    gridTab: 'Raster',
    quizTab: 'Quiz',
    displayTab: 'Weergave',
    gridTitle: 'Raster',
    gridDesc: 'Kolommen en schermstand.',
    portrait: 'Portret',
    portraitDesc: '(rechtop)',
    landscape: 'Liggend',
    landscapeDesc: '(gedraaid)',
    orientation: 'Schermstand',
    orientationDesc: '(forceer of automatisch)',
    auto: 'Automatisch',
    portraitMode: 'Portret',
    landscapeMode: 'Liggend',
    quizTitle: 'Snelheid',
    quizDesc: 'Tijdslimieten in milliseconden.',
    alwaysGood: 'Altijd goed',
    alwaysGoodDesc: '(≤ deze tijd = goed)',
    beatRecord: 'Record verslaan',
    beatRecordDesc: '(tolerantie boven record)',
    displayTitle: 'Weergave',
    displayDesc: 'Taal en kleuren.',
    highlightFound: 'Gevonden boeken',
    highlightFoundDesc: '(markeer gevonden boeken)',
    save: 'Opslaan',
    resetDefaults: 'Standaard',
  },
  en: {
    title: 'Bible Book Finder',
    subtitle: 'Learn where the books are located',
    studyMode: 'Study Mode',
    quizMode: 'Quiz Mode',
    score: 'Score',
    streak: 'Streak',
    best: 'Best',
    found: 'Found',
    of: 'of',
    time: 'Time',
    beat: 'Beat',
    tooSlow: 'Too slow',
    hebrewSection: 'HEBREW-ARAMAIC SCRIPTURES',
    greekSection: 'CHRISTIAN GREEK SCRIPTURES',
    correct: 'Correct!',
    wrong: 'Wrong',
    share: 'Share',
    shareText: 'I found {found} out of 66 Bible books!',
    resetProgress: 'Reset Progress',
    back: 'Back',
    settingsTitle: 'Settings',
    gridTab: 'Grid',
    quizTab: 'Quiz',
    displayTab: 'Display',
    gridTitle: 'Grid',
    gridDesc: 'Columns and orientation.',
    portrait: 'Portrait',
    portraitDesc: '(upright)',
    landscape: 'Landscape',
    landscapeDesc: '(rotated)',
    orientation: 'Orientation',
    orientationDesc: '(force or auto)',
    auto: 'Auto',
    portraitMode: 'Portrait',
    landscapeMode: 'Landscape',
    quizTitle: 'Speed',
    quizDesc: 'Time limits in milliseconds.',
    alwaysGood: 'Always good',
    alwaysGoodDesc: '(≤ this time = good)',
    beatRecord: 'Beat record',
    beatRecordDesc: '(tolerance above record)',
    displayTitle: 'Display',
    displayDesc: 'Language and colors.',
    highlightFound: 'Found books',
    highlightFoundDesc: '(highlight found books)',
    save: 'Save',
    resetDefaults: 'Defaults',
  }
};
